[package]
name = "tutorial_8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.2"
bevy-inspector-egui = "0.19.0"
bevy_rapier3d = "0.22.0"
bevy_third_person_camera = "0.1.0"
